name: Python application test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and write results to file
      run: |
        python -m unittest test_app.py > test_file.txt || true
    - name: Archive test file
      uses: actions/upload-artifact@v2
      with:
        name: test-file
        path: test_file.txt
